apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: company
spec:
  rules:
    - host: "<your-username-here>.lion7.dev"
      http:
        paths:
          - pathType: Prefix
            path: "/companies"
            backend:
              service:
                name: company
                port:
                  number: 8080
