apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maartenjan
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: company
    newName: registry.lion7.dev/craftsmen/kubernetes-for-developers-java:company-maarten-jan
