apiVersion: v1
kind: Service
metadata:
  name: company
  namespace: maartenjan
spec:
  selector:
    app: company
  ports:
    - name: http
      protocol: TCP
      appProtocol: HTTP
      port: 8080
      targetPort: 8081
