apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: maartenjan
spec:
  selector:
    app: employee
  ports:
    - name: http
      protocol: TCP
      appProtocol: HTTP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee
  namespace: maartenjan
spec:
  rules:
    - host: "maartenjan.lion7.dev"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: employee
                port:
                  number: 8080
