GET http://localhost:8081/company/hello

###

GET http://localhost:8081/company/average-monthly-salary/Bitter%20bier

###

GET http://localhost:8081/company/actuator/health
###

GET http://localhost:8081/company/actuator/health/readiness

###
